version: '3'

services:
  app:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000 & python manage.py runbot"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.3
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine 
    restart: unless-stopped
    env_file:
      - .env
    expose:
        - 6379
      
volumes:
  pgdata: {}